networks:
  frontend:
    name: camagru_frontend
  backend:
    name: camagru_backend

services:

  frontend:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
    networks:
      - frontend
    depends_on:
      - web
  web:
    build: .
    ports:
      - "80"
    volumes:
      - ./app:/var/www/html/app
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - frontend
      - backend
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/database:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  mysql_data:
    name: camagru_db_data